# Generated by Django 4.0 on 2021-12-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitelogo',
            old_name='title',
            new_name='name',
        ),
    ]
