# Generated by Django 4.0 on 2021-12-09 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title_sitelogo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name='Carousel Image'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='main/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg'])], verbose_name='Site Logo'),
        ),
    ]
