# Generated by Django 4.0 on 2021-12-09 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carousel_image_alter_sitelogo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Description'),
        ),
    ]
