# Generated by Django 4.0 on 2021-12-10 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_carousel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('why_chose', 'Why Chose')], max_length=50, verbose_name='Section Type')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('label', models.CharField(max_length=20, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(70), django.core.validators.MaxLengthValidator(70)], verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(70), django.core.validators.MaxLengthValidator(110)], verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='whychose/', verbose_name='Image')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
        ),
    ]
