# Generated by Django 4.0 on 2021-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesection_whychose'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
