# Generated by Django 4.0 on 2021-12-10 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesection_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(70), django.core.validators.MaxLengthValidator(100)], verbose_name='Description'),
        ),
    ]
