# Generated by Django 4.0 on 2021-12-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sitesection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychose',
            name='image',
        ),
        migrations.AddField(
            model_name='whychose',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='whychose/', verbose_name='Icon'),
        ),
    ]
